name: "Quality Assurance: codeception, phpstan, and ecs"
on:
  push:
      branches:
        - tests
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: ddev/github-action-setup-ddev@v1
    - name: Install dependencies
      run: ddev composer install
    - name: Run tests
      run: |
        mkdir _tests/_craft/storage
        ddev composer exec codecept build
        ddev composer run test

    # - name: Make code coverage badge
    #   uses: timkrase/phpunit-coverage-badge@v1.2.1
    #   with:
    #     coverage_badge_path: output/coverage.svg
    #     push_badge: false

    # - name: Git push to image-data branch
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     publish_dir: ./output
    #     publish_branch: image-data
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     user_name: 'github-actions[bot]'
    #     user_email: 'github-actions[bot]@users.noreply.github.com'
